# Generated by Django 2.1.5 on 2019-10-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='release_year',
            new_name='average_gross',
        ),
        migrations.AddField(
            model_name='series',
            name='highest_grossing_film',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='total_gross',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
