# Generated by Django 2.1 on 2019-10-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191018_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
